"""full_schema_v2

Revision ID: f99f2990e1ed
Revises: 0001_initial_schema
Create Date: 2026-09-05 15:47:15.873049
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types appear in autogenerated ops)


# revision identifiers, used by Alembic.
revision: str = 'f99f2990e1ed'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discountrule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_discount', sa.Float(), nullable=False),
    sa.Column('min_margin', sa.Float(), nullable=False),
    sa.Column('manager_approval_threshold', sa.Float(), nullable=False),
    sa.Column('finance_approval_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricelist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customersubscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'PENDING', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscriptionplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customersubscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customersubscription_customer_id'), ['customer_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('pricelistitem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('price_list_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['pricelist.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricelistitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricelistitem_price_list_id'), ['price_list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricelistitem_product_id'), ['product_id'], unique=False)

    op.create_table('upsellrule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_product_id', sa.Uuid(), nullable=False),
    sa.Column('promotion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('min_margin_impact', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['recommended_product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upsellrule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upsellrule_product_id'), ['product_id'], unique=False)

    op.create_table('negotiation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('rep_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACCEPTED', 'REJECTED', 'COUNTER_OFFERED', 'CLOSED', name='negotiationstatus'), nullable=False),
    sa.Column('requested_discount', sa.Float(), nullable=True),
    sa.Column('counter_discount', sa.Float(), nullable=True),
    sa.Column('final_discount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negotiation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiation_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('rep_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'PROCESSING', 'PICKING', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'OVERDUE', name='paymentstatus'), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('promised_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_quotation_id'), ['quotation_id'], unique=False)

    op.create_table('backorder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('required_qty', sa.Integer(), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('backorder_qty', sa.Integer(), nullable=False),
    sa.Column('expected_restock_date', sa.Date(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backorder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backorder_order_id'), ['order_id'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('outstanding_amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=False)

    op.create_table('negotiationmessage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('negotiation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('sender_role', sa.Enum('REP', 'CUSTOMER', 'MANAGER', 'SYSTEM', name='senderrole'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('discount_proposed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiation.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negotiationmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiationmessage_negotiation_id'), ['negotiation_id'], unique=False)

    op.create_table('orderline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orderline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orderline_order_id'), ['order_id'], unique=False)

    op.create_table('shipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('courier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('estimated_delivery', sa.Date(), nullable=True),
    sa.Column('actual_delivery', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', name='shipmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_order_id'), ['order_id'], unique=False)

    op.create_table('creditnote',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('credit_note_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creditnote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creditnote_credit_note_number'), ['credit_note_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_creditnote_customer_id'), ['customer_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('BANK_TRANSFER', 'CREDIT_CARD', 'CHEQUE', 'CASH', 'NET_30', 'NET_60', 'ACH', name='paymentmethod'), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_invoice_id'), ['invoice_id'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('address_billing', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address_shipping', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('rep_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', name='customerstatus'), nullable=False))
        batch_op.add_column(sa.Column('credit_limit', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key('fk_customer_rep_id_user', 'user', ['rep_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('variants', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=False)

    with op.batch_alter_table('stockinventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_units', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('incoming_units', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reorder_level', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_stockinventory_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stockinventory_warehouse_id'), ['warehouse_id'], unique=False)

    with op.batch_alter_table('subscriptionplan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_cycle', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billingcycle'), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('products', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('proration_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refund_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('billing_frequency')
        batch_op.drop_column('monthly_rate')
        batch_op.drop_column('annual_rate')

    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('replenishment_threshold', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('shipping_cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('replenishment_threshold')
        batch_op.drop_column('is_active')
        batch_op.drop_column('city')

    with op.batch_alter_table('subscriptionplan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_rate', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('monthly_rate', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('billing_frequency', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('refund_rules')
        batch_op.drop_column('cancellation_rules')
        batch_op.drop_column('proration_rules')
        batch_op.drop_column('products')
        batch_op.drop_column('description')
        batch_op.drop_column('price')
        batch_op.drop_column('billing_cycle')

    with op.batch_alter_table('stockinventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stockinventory_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stockinventory_product_id'))
        batch_op.drop_column('reorder_level')
        batch_op.drop_column('incoming_units')
        batch_op.drop_column('reserved_units')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('is_archived')
        batch_op.drop_column('image_url')
        batch_op.drop_column('variants')
        batch_op.drop_column('sku')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('payment_terms')
        batch_op.drop_column('credit_limit')
        batch_op.drop_column('status')
        batch_op.drop_column('rep_id')
        batch_op.drop_column('tax_id')
        batch_op.drop_column('address_shipping')
        batch_op.drop_column('address_billing')
        batch_op.drop_column('phone')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_invoice_id'))

    op.drop_table('payment')
    with op.batch_alter_table('creditnote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creditnote_customer_id'))
        batch_op.drop_index(batch_op.f('ix_creditnote_credit_note_number'))

    op.drop_table('creditnote')
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_order_id'))

    op.drop_table('shipment')
    with op.batch_alter_table('orderline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orderline_order_id'))

    op.drop_table('orderline')
    with op.batch_alter_table('negotiationmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiationmessage_negotiation_id'))

    op.drop_table('negotiationmessage')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoice_customer_id'))

    op.drop_table('invoice')
    with op.batch_alter_table('backorder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backorder_order_id'))

    op.drop_table('backorder')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_order_customer_id'))

    op.drop_table('order')
    with op.batch_alter_table('negotiation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiation_quotation_id'))

    op.drop_table('negotiation')
    with op.batch_alter_table('upsellrule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upsellrule_product_id'))

    op.drop_table('upsellrule')
    with op.batch_alter_table('pricelistitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricelistitem_product_id'))
        batch_op.drop_index(batch_op.f('ix_pricelistitem_price_list_id'))

    op.drop_table('pricelistitem')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('customersubscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customersubscription_customer_id'))

    op.drop_table('customersubscription')
    op.drop_table('pricelist')
    op.drop_table('discountrule')
    # ### end Alembic commands ###
